### ISSUE TITLE
Having trouble setting up clocks for samc21

### ISSUE THREAD

**Issue by Bexin3** [prices/ArduinoCore-samd#4]
Hi, I am trying to setup clocks by editing registers for samc21, however I can't find any functions that are supposed to be there based on data sheet that would allow me to do this, trying to move over this code from SAMD21, but I can't find registers like GCLK->GENCTRLn mentioned in data sheet.

  ```
REG_GCLK_GENDIV = GCLK_GENDIV_DIV(dFactor) | GCLK_GENDIV_ID(clk);  // Select Generic Clock (GCLK) 4
  while (GCLK->STATUS.bit.SYNCBUSY)
    ;  // Wait for synchronization

  REG_GCLK_GENCTRL = GCLK_GENCTRL_IDC |          // Set the duty cycle to 50/50 HIGH/LOW
                     GCLK_GENCTRL_GENEN |        // Enable GCLK4
                     GCLK_GENCTRL_SRC_DFLL48M |  // Set the 48MHz clock source
                     GCLK_GENCTRL_ID(clk);    // Select GCLK4


  while (GCLK->STATUS.bit.SYNCBUSY)
```

**Comment by prices** [comment]
The clocks on the SAMC21 are significantly different and have a different setup from the SAMD21.  Is this a bug in this project?  It seems more like a question on porting SAMD21 to SAMC21.

**Comment by Bexin3** [comment]
Hi, they are indeed quite different, however I also wasn't able to set them up based on what the data sheet suggests should work, though I may be doing something wrong
When I write GCLK -> 
There is no GENCTRLn option, despite data sheet mentioning is. I was able to rewrite the ADC program I made to work with samc21, but here I can't get it to work, GCLK-> group doesn't seem to have any commands it should

**Comment by prices** [comment]
You have not given me anywhere near enough information to debug this.  The options exist, and work because I am using them in my projects.  I don't know why they are not working for you.  I wish I had time to help you debug it, but I don't right now.  Sorry.

If you can come back with an actual problem in this project, I will be happy to help you.

**Comment by Bexin3** [comment]
Hi, could you send me an example of your project where it works? Just so I can see how to do it so it works without wasting your time.

**Comment by prices** [comment]
GCLK->GENCTRL[0].reg = (GCLK_GENCTRL_DIV(2) | GCLK_GENCTRL_SRC_DPLL96M | GCLK_GENCTRL_IDC | GCLK_GENCTRL_GENEN);

**Comment by Bexin3** [comment]
Hi, thanks a lot!! I see what I was doing wrong.
